module.exports = {
  username: '#loginId',
  password: '#password',
  home: 'div.view-segment-dashboard',
  baseList: 'div.baseLanguage',
  targetList: 'div.targetLanguage',
  startButton: 'button#start-button-main',
  modalQuestion: 'td#question-field',
  modalCorrectAnswer: 'td#correct-answer-field',
  modalUserAnswered: 'td#users-answer-field',
  modal: 'div[uib-modal-window=modal-window]',
  modalBackdrop: 'div[uib-modal-backdrop=modal-backdrop]',
  question: '#question-text',
  answerBox: 'input#answer-text',
  exitButton: 'button.exit-button',
  exitContinueButton: 'button.continue-button',
  continueButton: 'button#continue-button',
};
